### PR TITLE
Revert "OD-100 [Feature] Optimization Api calls for data source manager"

### PR DESCRIPTION
**Pull request by sofiiakvasnevska**
Reverts Fliplet/fliplet-widget-data-source#107

### CODE REVIEW

**Comment by squallstar** [comment]
@sofiiakvasnevska what's the reason for reverting this?

**Comment by sofiiakvasnevska** [comment]
@squallstar because we made a mistake in widget.json and merged it without seeing it
Screenshot 2020-11-18 at 16 53 07

and we have created the correct one https://github.com/Fliplet/fliplet-widget-data-source/pull/108#pullrequestreview-532555249 which you have approved

so could you please approve the revert

**Comment by squallstar** [comment]
@sofiiakvasnevska I don't understand, can't you just merge https://github.com/Fliplet/fliplet-widget-data-source/pull/108 ?

**Comment by sofiiakvasnevska** [comment]
@squallstar so if I merge #108 it will be corrected, right?

**Comment by squallstar** [comment]
@sofiiakvasnevska yes

**Pull request closed without merging**
