### PR TITLE
Allow the data sources widget to initialise filtered by appId

### PR DESCRIPTION
**Pull request by hcarneiro**
This enhancement is for when a user clicks on App Data from the right side bar in Edit, the overlay with the list of data sources, only shows the data sources used by the app.

Studio commit reference: https://github.com/Fliplet/fliplet-studio/pull/3386/commits/f5eb3d421e555ff0ee7d3e0e0efe95b16c008769

screenshot 2018-10-31 at 13 19 53

### CODE REVIEW

**Comment by ibroom** [comment]
@hcarneiro will you be including a way that users can select an app in the data source manager to see only data sources related to that app? e.g. an interactive way to apply the filter?

**Comment by hcarneiro** [comment]
@tonytlwu This last commit adds the following:
- Added Last updated column
- Allow users to sort by Last updated or Data source name
- Added a button to see all the data sources when see the list filtered by the app
- UI tweaks (vertically align rows, remove the `<code>` from the IDs)

**Comment by hcarneiro** [comment]
@ibroom We just did some other enhancements but we didn't think of that scenario. Can be done though!

**Comment by tonytlwu** [comment]
@hcarneiro I'd say **a way that users can select an app in the data source manager to see only data sources related to that app** is actually the more useful feature compared to the other changes. If @ibroom wasn't clear, I think it should've been the only thing that needed implementing. Can we implement it as part of this PR?

**Comment by hcarneiro** [comment]
@tonytlwu As with anything we could add as many features as we can think of, but this PR isn't for that. This will already filter the data sources in context of the app you are editing. We can later enhance the component so that when accessed by the App Data link found in the apps list page, the user can filter by app.

**Pull request merged**
