### PR TITLE
OD-450 [Fix] Parse nested arrays and objects for render in spreadsheet correctly

### PR DESCRIPTION
**Pull request by ivandevupp**
@sofiiakvasnevska
## Issue
OD-450 https://weboo.atlassian.net/browse/OD-450
## Description
Parse nested arrays and objects for render in spreadsheet correctly
## Screenshots/screencasts
https://monosnap.com/file/MdPV4ocMYAKreLFsf8fdEEEqRmJPFr
## Backward compatibility
This change is fully backward compatible.
## Reviewers 
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii

### CODE REVIEW

**Comment by squallstar** [comment]
Can you confirm the data is saved back to json when read via the APIs?

**Comment by ivandevupp** [comment]
> Can you confirm the data is saved back to json before saving? Please check that when reading after saving the data is actually a JSON rather than a JSON string.

@squallstar Because of `prepareData` fires on first table render and in `afterChangesObserved` hook, data is stringified only on render and it is not saved back as a JSON string, because users can save datasource only after changes are made, but if changes are made we don't change data in `prepareData` function.

**Comment by squallstar** [comment]
@ivandevupp does it mean that if I make a change to the string then it's not converted back to a JSON? If so, that's basically breaking the functionality we want to give users.

They should be able to amend the JSON and such JSON should correctly be saved as a JSON (not a JSON string) when the record is updated. @tonytlwu can you confirm?

**Comment by ivandevupp** [comment]
> @ivandevupp does it mean that if I make a change to the string then it's not converted back to a JSON? If so, that's basically breaking the functionality we want to give users.
> 
> They should be able to amend the JSON and such JSON should correctly be saved as a JSON (not a JSON string) when the record is updated. @tonytlwu can you confirm?

@squallstar I added functionality that allows users to amend and correctly save the JSON values.
WHEN we add entries with JSON props to the datasource, they are added and rendered correctly:
image
image

WHEN we change some JSON value and commit it to the datasource:
image

THEN after page reload we have correct data in query:
image

**Comment by squallstar** [comment]
@ivandevupp it looks like you're parsing all inputs into JSON, which will result in some strings being casted to a Number or Boolean or else (e.g. `JSON.parse("false")` is `false`) and we don't want that. Please only parse JSON strings that are either objects or arrays, e.g. they start either with `{` or `[`

**Comment by ivandevupp** [comment]
@squallstar Update with parsing only JSON strings that are either objects or arrays by regexp: `^({|\[).*(}|\])$`

**Comment by squallstar** [comment]
@ivandevupp can you update the regexp to allow empty spaces before and after the json object? e.g. `[ ]*`

**Comment by ivandevupp** [comment]
@squallstar you mean `^[\s]*({|\[).*(}|\])[\s]*$` ?

**Comment by squallstar** [comment]
@ivandevupp yes, that works.

**Review by squallstar — APPROVED** [review]
@sofiiakvasnevska this is ready to be deployed on **staging** for QA.

- **Risk**: Critical
- **Affected**: Studio users managing data sources
- **Verify**: Verify data in data sources (including JSON data) can be managed

**Pull request merged**
